# Generated by Django 4.2.5 on 2023-11-28 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('13e594a0-4127-4fb8-aaf6-880668b0a678'), editable=False, primary_key=True, serialize=False),
        ),
    ]
